// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNf7y0k0kd5b5dKx4o8mmIvs9w6D1lIrU',
    appId: '1:207586335919:web:c6e637b98b4af5ed34885a',
    messagingSenderId: '207586335919',
    projectId: 'fir-auth-176f8',
    authDomain: 'fir-auth-176f8.firebaseapp.com',
    storageBucket: 'fir-auth-176f8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP4eRCSjnOa_d_FhyZ7lHVDj0RQe_yFgA',
    appId: '1:207586335919:android:b5dc7c8ab1f57b6534885a',
    messagingSenderId: '207586335919',
    projectId: 'fir-auth-176f8',
    storageBucket: 'fir-auth-176f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCLdQVH6bLbG1E0ncF6q6RsGMAV9_Ihow',
    appId: '1:207586335919:ios:4461c32f4131360634885a',
    messagingSenderId: '207586335919',
    projectId: 'fir-auth-176f8',
    storageBucket: 'fir-auth-176f8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCLdQVH6bLbG1E0ncF6q6RsGMAV9_Ihow',
    appId: '1:207586335919:ios:4461c32f4131360634885a',
    messagingSenderId: '207586335919',
    projectId: 'fir-auth-176f8',
    storageBucket: 'fir-auth-176f8.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNf7y0k0kd5b5dKx4o8mmIvs9w6D1lIrU',
    appId: '1:207586335919:web:f3be79d3aff8208334885a',
    messagingSenderId: '207586335919',
    projectId: 'fir-auth-176f8',
    authDomain: 'fir-auth-176f8.firebaseapp.com',
    storageBucket: 'fir-auth-176f8.firebasestorage.app',
  );
}
